"""initial

Revision ID: 1d5eef404bbf
Revises: 
Create Date: 2026-02-21 20:40:19.290678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d5eef404bbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender_enum'), autoincrement=False, nullable=False),
    sa.Column('height', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=False),
    sa.Column('goal_weight', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=False),
    sa.Column('preferred_theme', postgresql.ENUM('light', 'dark', name='theme_enum'), autoincrement=False, nullable=False),
    sa.Column('preferred_weight_unit', postgresql.ENUM('kg', 'lbs', name='weight_unit_enum'), autoincrement=False, nullable=False),
    sa.Column('preferred_height_unit', postgresql.ENUM('cm', 'feet', name='height_unit_enum'), autoincrement=False, nullable=False),
    sa.Column('subscription_plan', postgresql.ENUM('free', 'premium', name='subscription_plan_enum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('bmi', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('bmr', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('age', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('auth_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint('age >= 6 AND age <= 150', name=op.f('age_valid')),
    sa.CheckConstraint('goal_weight > 40::numeric AND goal_weight <= 200::numeric', name=op.f('goal_weight_valid')),
    sa.CheckConstraint('height > 100::numeric AND height <= 300::numeric', name=op.f('height_valid')),
    sa.CheckConstraint('weight > 30::numeric AND weight <= 800::numeric', name=op.f('weight_valid')),
    sa.ForeignKeyConstraint(['auth_id'], ['auth.users.id'], name=op.f('users_auth_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('auth_id', name=op.f('users_auth_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
