"""added steps table + modified_at column for multiple tables

Revision ID: 3eb297914930
Revises: 28412cb7fa4b
Create Date: 2026-05-04 21:39:30.543132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eb297914930'
down_revision: Union[str, Sequence[str], None] = '28412cb7fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_secs', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_user_id'), 'steps', ['user_id'], unique=False)
    op.add_column('weight_logs', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('weight_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('weight_logs', 'logged_at')
    op.add_column('workout_notes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workout_notes', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workout_plans', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workout_plans', 'updated_at')
    op.add_column('workout_sets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workout_sets', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'modified_at')
    op.drop_column('workout_sets', 'created_at')
    op.add_column('workout_plans', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('workout_plans', 'modified_at')
    op.drop_column('workout_notes', 'modified_at')
    op.drop_column('workout_notes', 'created_at')
    op.add_column('weight_logs', sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('weight_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('weight_logs', 'modified_at')
    op.drop_index(op.f('ix_steps_user_id'), table_name='steps')
    op.drop_table('steps')
    # ### end Alembic commands ###
