"""added the workout and weight tables

Revision ID: 5d8ad10dd485
Revises: 3d23c1bf0b2e
Create Date: 2026-04-25 22:07:04.155314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d8ad10dd485'
down_revision: Union[str, Sequence[str], None] = '3d23c1bf0b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('primary_muscle', sa.Enum('chest', 'back', 'shoulders', 'biceps', 'triceps', 'forearms', 'core', 'glutes', 'quads', 'hamstrings', 'calves', 'full_body', 'cardio', name='musclegroup'), nullable=False),
    sa.Column('secondary_muscles', sa.String(length=255), nullable=True),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'cable', 'machine', 'bodyweight', 'kettlebell', 'bands', 'other', name='equipment'), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('is_bilateral', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Enum('strength', 'hypertrophy', 'endurance', 'weight_loss', 'maintenance', name='plangoal'), nullable=True),
    sa.Column('duration_weeks', sa.SmallInteger(), nullable=True),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plan_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('day_order', sa.SmallInteger(), nullable=False),
    sa.Column('day_label', sa.String(length=80), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('prescribed_sets', sa.SmallInteger(), nullable=True),
    sa.Column('prescribed_reps', sa.String(length=20), nullable=True),
    sa.Column('prescribed_rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('rest_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_order', 'position', name='uq_plan_day_position')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_day', sa.SmallInteger(), nullable=True),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_dropset', sa.Boolean(), nullable=False),
    sa.Column('is_failure', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('weight_logs', sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('weight_logs', sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('weight_logs', sa.Column('muscle_mass_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('weight_logs', sa.Column('water_pct', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('weight_logs', sa.Column('visceral_fat', sa.SmallInteger(), nullable=True))
    op.add_column('weight_logs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('weight_logs', sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('weight_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('weight_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('weight_logs', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_weight_logs_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_timestamp'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_constraint(op.f('uq_user_timestamp'), 'weight_logs', type_='unique')
    op.drop_column('weight_logs', 'timestamp')
    op.drop_column('weight_logs', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_logs', sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('weight_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_timestamp'), 'weight_logs', ['user_id', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_weight_logs_timestamp'), 'weight_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_weight_logs_id'), 'weight_logs', ['id'], unique=False)
    op.alter_column('weight_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('weight_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('weight_logs', 'created_at')
    op.drop_column('weight_logs', 'logged_at')
    op.drop_column('weight_logs', 'notes')
    op.drop_column('weight_logs', 'visceral_fat')
    op.drop_column('weight_logs', 'water_pct')
    op.drop_column('weight_logs', 'muscle_mass_kg')
    op.drop_column('weight_logs', 'body_fat_pct')
    op.drop_column('weight_logs', 'weight_kg')
    op.create_foreign_key(op.f('users_auth_id_fkey'), 'users', 'users', ['auth_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_table('workout_sets')
    op.drop_table('workout_sessions')
    op.drop_table('workout_plan_exercises')
    op.drop_table('workout_plans')
    op.drop_table('exercises')
    # ### end Alembic commands ###
