"""modified prescribed_reps

Revision ID: 99806253af87
Revises: 3eb297914930
Create Date: 2026-05-04 21:50:48.776246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99806253af87'
down_revision: Union[str, Sequence[str], None] = '3eb297914930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_plan_exercises', 'prescribed_reps',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.INT4RANGE(),
               existing_nullable=True,
                   postgresql_using="""
        int4range(
            split_part(prescribed_reps, '-', 1)::int,
            split_part(prescribed_reps, '-', 2)::int,
            '[]'
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_plan_exercises', 'prescribed_reps',
               existing_type=postgresql.INT4RANGE(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
