"""changed db structure

Revision ID: cbe6a9361517
Revises: 5d8ad10dd485
Create Date: 2026-05-03 22:37:21.633975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe6a9361517'
down_revision: Union[str, Sequence[str], None] = '5d8ad10dd485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logged_date', name='uq_workout_notes_user_date')
    )
    op.drop_table('workout_sessions')
    op.drop_constraint(op.f('users_auth_id_fkey'), 'users', type_='foreignkey')
    op.add_column('workout_sets', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('workout_sets', sa.Column('logged_date', sa.Date(), nullable=False))
    op.drop_constraint(op.f('workout_sets_session_id_fkey'), 'workout_sets', type_='foreignkey')
    op.create_foreign_key(None, 'workout_sets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_sets', 'session_id')
    op.drop_column('workout_sets', 'logged_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workout_sets', sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.create_foreign_key(op.f('workout_sets_session_id_fkey'), 'workout_sets', 'workout_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_sets', 'logged_date')
    op.drop_column('workout_sets', 'user_id')
    op.create_foreign_key(op.f('users_auth_id_fkey'), 'users', 'users', ['auth_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_table('workout_sessions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_day', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('training_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('workout_sessions_plan_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workout_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_sessions_pkey'))
    )
    op.drop_table('workout_notes')
    # ### end Alembic commands ###
